import Head from "next/head";

export default function Home() {
  return (
      <div>
        <Head>
          <title>Arham</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        {/* body */}
        <main>
          <h1>ARHAM RAZA</h1>        
        </main>
      </div>
  );
}

